# .github/workflows/renovate.yml
name: Renovate (CLI)

on:
  schedule:
    # JST 06:00 土曜 = UTC 金曜 21:00
    - cron: "0 21 * * 5"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json5
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: github
          LOG_LEVEL: info
